### ISSUE TITLE
optical flow of somethong to something v1?

### ISSUE THREAD

**Issue by BoyuanJiang** [metalbubble/TRN-pytorch#38]
Can you provide the optical flow of something-something v1? Or can you tell me how to extract it? Since there are only jpegs in the dataset (not a video file). Thanks~

**Comment by mangdian** [comment]
+1

**Comment by alexandonian** [comment]
Hi, you should be able to download something-something-v1 optic flow here:
http://relation.csail.mit.edu/data/20bn-something-something-v1-flow.tar.gz

-Alex

**Comment by mangdian** [comment]
@alexandonian  thanks, but there is some error in this file, since the data is about 500MB, which is too small for something-something dataset. And I failed to decompress it. The error information is as blow:
`gzip: stdin: unexpected end of file
flow/29336/00008.jpg
flow/29336/00001.jpg
flow/29336/00006.jpg
flow/29336/00018.jpg
flow/29336/00011.jpg
flow/29336/00016.jpg
flow/29336/00023.jpg
flow/29336/00024.jpg
flow/29336/00007.jpg
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
`

**Comment by alexandonian** [comment]
Hi,
I replaced the file, which is now about 4.8Gb, and was able to extract the flow images. I believe it has been corrected now. Can you give it another try? It is the same link.

-Alex

**Comment by BoyuanJiang** [comment]
it works, thank you

**Comment by BoyuanJiang** [comment]
@alexandonian After I unzip it, the files like 000001.jpg... Should not be something like x_000001.jpg and y_000001.jpg?
